### ISSUE TITLE
Zeroes and O letter in URL look the same

### ISSUE THREAD

**Issue by SecT0uch** [httpie/desktop#1]
Pretty much everything is in the title.
![image](https://user-images.githubusercontent.com/26085417/154048571-0f719231-075a-435b-b6be-a8619e824371.png)

OS: Manjaro
Latest AppImage

**Comment by SecT0uch** [comment]
I would like to add: backticks (`) are invisible

**Comment by jakubroztocil** [comment]
Yes, thanks. And the 3rd font issue we plan to fix is that curly braces and brackets are not distinct enough (`[{}]`).

**Comment by jakubroztocil** [comment]
We’ve [just released 2022.7.0](https://httpie.io/blog/changelog-0014)  with a number of tweaks to the font. Keeping this open because the `0` vs `O` issue is the one still pending.

**Comment by jakubroztocil** [comment]
This has just been fixed — https://httpie.io/blog/changelog-0016

![image](https://user-images.githubusercontent.com/326885/169107121-a3bd4f08-ea47-4826-b757-c1c1b6c2fbe6.png)
