### ISSUE TITLE
[Bug]: Display Issue on M1 / Response Menu

### ISSUE THREAD

**Issue by craigz** [httpie/desktop#10]
### What happened?

There is a menu in the response section, labeled Response.

When selected, a grey background appears with two green checkmarks and no text/label by either.  
Selecting 1 or the other and returning makes no change in the state of the checks. They both remain in an identical state and colored green, so there is no appearance of a selection being made. 

This being in dark mode on an M1 running macOS 12.2.1.  

Using httpie release 2022.6.0 (2022.6.0).

<img width="125" alt="httpieResponse" src="https://user-images.githubusercontent.com/1929275/157998357-89f5639e-c0c2-4164-a7d6-ab0d6cc78dbc.png">

### Steps to reproduce?

```Markdown
- launch the app.
- select the response label to the right of the params label. 
- click the button and see a pair of green checkmarks with nothing to choose.
- pseudo click one if you like, nothing changes.

- note: this happens no matter what is selected in the library; be it a draft, a sent request, or a new request. 

in all cases i've checked the button discloses the same 2 'options' with both checks in place.
```

### What did you expect to happen?

I expected to select something which would optionally modify the text in the results section. 

### Platform

MacOS ARM64

### HTTPie Desktop version

2022.6.0 (2022.6.0)

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by jakubroztocil** [comment]
Thanks, @craigz! We’re on ti.
