### ISSUE TITLE
[Bug]: URL HOST and PORT variables 

### ISSUE THREAD

**Issue by kynrai** [httpie/desktop#102]
### What happened?

It does not appear to be possible to have a colon for a port when using variables

### Steps to reproduce?

```Markdown
Set. host and port variable
try
`http://{{HOST}}:{{PORT}}`
```

### What did you expect to happen?

Expect the URL to be valid

### Platform

macOS

### HTTPie Desktop version

2022.5.1

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by jkbrzt** [comment]
@kynrai thanks for the report. We’ll look into it  👀

**Comment by berazo29** [comment]
It works if you set the var with the colons on the env variable.
For example `API_PORT = :3000 ` then use on the url as `GET localhost{{API_PORT}}/foo`. 
I think it should be fixed but for now this workout does the job.

**Comment by kynrai** [comment]
The workaround works well for now, is this supposed to be fixed in the latest version? just checked on `Version 2023.3.6 (2023.3.6)` and its still an issue, I dont mind trying to fix it if i have time to look into this

**Comment by jkbrzt** [comment]
✅ Fixed in [v2024.1.1 →](https://github.com/httpie/desktop/releases/tag/v2024.1.1)
