### ISSUE TITLE
[Bug]: Auth headers are put as query string

### ISSUE THREAD

**Issue by ibuki2003** [httpie/desktop#103]
### What happened?

When I set the Bearer token the Authorization *header* is placed at the URL, as a query string.

### Steps to reproduce?

```Markdown
1. Open the Auth tab
2. Switch to `API key` and select `As param`
3. Back to `Bearer token`
4. The token appears in the query string
```

### What did you expect to happen?

Basic auth and Bearer token are expected to be set as a header 

### Platform

Linux

### HTTPie Desktop version

2023.3.5

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by jkbrzt** [comment]
@ibuki2003, there’s a "Bearer token” auth option:

<img width="987" alt="Screenshot 2023-09-06 at 15 10 25" src="https://github.com/httpie/desktop/assets/326885/1771a26c-24e8-40b9-9989-6fbe98919609">


The ”API key” option is for when you want to pass the auth via a custom header or URL parameter.

**Comment by ibuki2003** [comment]
@jkbrzt Thank you for your reply.
I know the Bearer token option. The problem is that the Bearer token is inserted as a query parameter.
Please see the image below.

![image](https://github.com/httpie/desktop/assets/28347743/74f8ae95-30f4-4d0d-a85e-7caccc0344bb)

**Comment by jkbrzt** [comment]
@ibuki2003 apologies — I missed the part about switching back. This is indeed a bug.
