### ISSUE TITLE
Missing options of ignoring validity of SSL certificates

### ISSUE THREAD

**Issue by aschroeder27** [httpie/desktop#11]
While testing my API i got the following error:
![image](https://user-images.githubusercontent.com/59775787/160378799-6c108aff-5b38-4a0f-b083-8b569632ea4d.png)

An option to ignore invalid, missing or self-signed certificates would be key here.

**Comment by victorgram** [comment]
+1

**Comment by daavidkllr** [comment]
+1

**Comment by geertw** [comment]
Missing this one as well, is there any progress on this issue?

**Comment by daavidkllr** [comment]
Same here, it would be nice if this one gets more attention, it blocks the usage of the desktop client for me. 🙏🏽

**Comment by jakubroztocil** [comment]
Hello everyone! Thank you so much for your feedback. We’ve just released a new version that allows you to disable SSL verification. 

See changelog: https://httpie.io/blog/changelog-0017

![image](https://user-images.githubusercontent.com/326885/182688543-d88723f0-74d7-4b45-bf9d-7838d77601b2.png)

![image](https://user-images.githubusercontent.com/326885/182688565-4537afe1-7484-4cad-9191-5483c5652ee3.png)

**Comment by deviantony** [comment]
Ah! I was looking for that one! Nice :)

**Comment by MIvanIsten** [comment]
Configuration option to ca.pem would be useful too.
