### ISSUE TITLE
[Feature]: Show variable value on hover

### ISSUE THREAD

**Issue by tahsinature** [httpie/desktop#110]
### What happened?

It sometimes gets annoying to go back and forth between the request and environment page to see which value a variable using.
It would  be nicer if we could see the current value by hovering over the variable.

### Steps to reproduce?

```Markdown
1. Use a variable. It can be in the URL / Headers / Body.
2. Try to see what's the value of the variable.
```

### What did you expect to happen?

To show the current value of the variable.

### Platform

macOS

### HTTPie Desktop version

2022.5.1

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by jkbrzt** [comment]
Hey @tahsinature, thanks for reaching out.  

You should be able to see the variable value in a simple tooltip on hover — does it not appear for you?

<img width="378" alt="image" src="https://github.com/httpie/desktop/assets/326885/9ded40eb-bf4e-4693-a85d-c3ec9f054de1">



## Coming soon

We have a new version in the works that will improve the variable UI/UX.

Upcoming variables auto-complete:
<img width="372" alt="image" src="https://github.com/httpie/desktop/assets/326885/c662395a-8fd9-4b8f-990c-f623d0ca01d6">

<br>

Upcoming variables context menu with many useful actions:
<img width="324" alt="image" src="https://github.com/httpie/desktop/assets/326885/572b25ad-faa2-4035-8e63-0c60598c069f">
