### ISSUE TITLE
Why header params first word to convert uppercase?

### ISSUE THREAD

**Issue by anigkus** [httpie/desktop#120]
### What happened?

Look this，Please。
 
<img width="773" alt="image" src="https://github.com/httpie/desktop/assets/88264073/f965434e-c072-42ab-a1ed-c2bf6a42db3c">

### Steps to reproduce?

```Markdown
1、Open HTTPie
2、New Request
3、Setting some header params
```

### What did you expect to happen?

Not convert header param

### Platform

macOS

### HTTPie Desktop version

Version 2023.3.6 (2023.3.6)

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by arielumg** [comment]
Same here, and it shouldn't happen as for example at the request i'm trying to do a GET needs an specific header that begins lowercase, but the GUI is automatically sending it as first letter uppercase.
