### ISSUE TITLE
[Feature Request]: Graphql Autocompletion

### ISSUE THREAD

**Issue by madrussa** [httpie/desktop#124]
Probably quite the task, but adding suggestions, autocompletion and validation on GraphQL would be really powerful. Given the user adds their GraphQL endpoint you can begin to check that the grapql being written is valid, and suggest completions.

I use [Apollo Playground](https://www.apollographql.com/docs/apollo-server/v2/testing/graphql-playground/) which is built into apps. However this isn't available on production sites so being able to have the nice features of the playground built into HTTPie would make HTTPie far more attractive.

**Comment by jkbrzt** [comment]
Hey @madrussa, have you seen this?

https://httpie.io/blog/changelog-0018#support-for-graphql-apis

**Comment by madrussa** [comment]
Nope, works for me 👍  thank you!
