### ISSUE TITLE
[Bug]: Login with Github not working on Desktop

### ISSUE THREAD

**Issue by blaqshyd** [httpie/desktop#126]
### What happened?

Login with Github doesn't work on HTTPIE Desktop on Kali linux  :cry: 

### Steps to reproduce?

```Markdown
1. Launch the app
2. Click on Settings and more
3. Click on Login with Github and click Continue
```

### What did you expect to happen?

I expected the app to authorize with github as it did on the web version

### Platform

Linux

### HTTPie Desktop version

2023.3.6

### Relevant log output

```Shell
Failed to open URI
The specified location is not supported.
```

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by jkbrzt** [comment]
Hey @blaqshyd, perhaps you missed the Linux-specific installation instructions that require AppImageLauncher?

> Please follow the instructions below to install HTTPie for Desktop on Linux. 
> ⚠️ The Linux package uses [AppImage](https://appimage.org/), and you need to install it using [AppImageLauncher](https://github.com/TheAssassin/AppImageLauncher) for the app to work:
> 1. Install [AppImageLauncher](https://github.com/TheAssassin/AppImageLauncher) ([instructions](https://github.com/TheAssassin/AppImageLauncher#system-wide-installation))
> 2. Download `HTTPie-*.AppImage` (or `HTTPie-*arm64.AppImage` for ARM64 architecture) from [the latest release](https://github.com/httpie/desktop/releases/latest) page
> 3. Run `$ AppImageLauncher HTTPie-*.AppImage`

—https://github.com/httpie/desktop#linux

**Comment by blaqshyd** [comment]
Ohhh yes, I guess that was why. I tried installing the AppImageLauncher but couldn't get it to work so I moved on to install the AppImage in the terminal. I went through the process again just now and it works. Login with Github works now. Thanks
