### ISSUE TITLE
Mobile app?

### ISSUE THREAD

**Issue by NebulaTechs** [httpie/desktop#159]
请问可以支持移动端应用吗

**Comment by jkbrzt** [comment]
Hi @NebulaTechs, while we don’t plan on providing a dedicated mobile at the moment, the web version of the app is fully touch and mobile optimized:

https://httpie.io/docs/desktop/mobile-and-touch-support

![image](https://github.com/httpie/desktop/assets/326885/40d16edb-c054-41bc-b0e9-1453b770e347)
