### ISSUE TITLE
[Bug]: The icon within the More menu button is not centered

### ISSUE THREAD

**Issue by iAmWillShepherd** [httpie/desktop#17]
### What happened?

The ellipses aren't centered.

<img width="1385" alt="Screen Shot 2022-04-26 at 10 49 08 AM" src="https://user-images.githubusercontent.com/1715082/165341519-63c21080-aadc-4f89-9be7-0582dcb44ec7.png">

### Steps to reproduce?

```Markdown
1. Launch the app
2. Hover mouse over More... menu button
```

### What did you expect to happen?

The ellipses should be centered within the parent container. 

### Platform

macOS

### HTTPie Desktop version

2022.5.1

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by jakubroztocil** [comment]
Thanks, well spotted, @iAmWillShepherd! We’ll fix it.

**Comment by jakubroztocil** [comment]
(Btw, you can use the `:3000` localhost shortcut from the CLI — https://httpie.io/docs/cli/url-shortcuts-for-localhost.)

**Comment by jakubroztocil** [comment]
Fixed! https://httpie.io/blog/changelog-0015
