### ISSUE TITLE
Why is the WebApp sending requests through a proxy?

### ISSUE THREAD

**Issue by saljic** [httpie/desktop#180]
While trying out the web app my colleague noticed that when sending requests it goes through a proxy.

Can anyone explain why this is necessary?

![image](https://github.com/httpie/cli/assets/2689662/d697c44e-9a41-43e6-9478-e49819e09311)

**Comment by jkbrzt** [comment]
Hi @saljic, the web app needs to use a proxy to avoid problems with CORS because requests are sent using the browser’s `fetch()`, which comes with this limitation. The desktop and CLI apps aren’t limited in this way, so they make requests directly.
