### ISSUE TITLE
Feature request: `OPTIONS` method for requets.

### ISSUE THREAD

**Issue by henryh9n** [httpie/desktop#2]
I don't know if this is the best place to write this, but it would have been nice to have the ability to make `OPTIONS` requests.
As far as I see it is possible to do from the command line but not from the desktop app.
Maybe some other request method will come handy too, for instance `HEAD` and `COPY`.

**Comment by jakubroztocil** [comment]
Thanks, @henryh9n. We’ve added it to our backlog.

**Comment by jakubroztocil** [comment]
This has just been shipped — https://httpie.io/blog/changelog-0016

![image](https://user-images.githubusercontent.com/326885/169107490-29b72721-e0b8-4358-a713-ba8e05beb3b8.png)

**Comment by henryh9n** [comment]
@jakubroztocil Perfect! Thanks!
