### ISSUE TITLE
[Bug]: Not sending requests

### ISSUE THREAD

**Issue by estruyf** [httpie/desktop#20]
### What happened?

The desktop version doesn't give me a response to the request. It seems that it never initiates the request.

### Steps to reproduce?

```Markdown
- Entered the `​https://frontmatter.codes/api/stars` URL
- Clicked on send
- Request panel updates, but the request doesn't seem to get sent
```

https://user-images.githubusercontent.com/2900833/165730232-5b156ae8-e75f-40f0-993c-fe71829f9912.mp4

### What did you expect to happen?

I would hope for a response to come back.

### Platform

macOS

### HTTPie Desktop version

2022.7.0

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by psd-coder** [comment]
Hi! Your URL starts from zero width space char. You can make sure in that by opening preview panel: 
![image](https://user-images.githubusercontent.com/68564223/165737704-789299f8-d2ba-496a-8ee1-e2f5df827e15.png)

**Comment by estruyf** [comment]
Cool! Thanks 🙏

**Comment by jakubroztocil** [comment]
Thanks for the report @estruyf! We’ll make this type of issue more transparent in a future release.
