### ISSUE TITLE
Feature request: Make JSON responses searchable

### ISSUE THREAD

**Issue by nurettinabaci** [httpie/desktop#23]
# Checklist
- [x] I've searched for similar feature requests.

# Enhancement request
Add ability to search inside JSON response via CTRL+F, or Right-click > Select 'Search text'

# Problem it solves
JSON response text will be searchable.

**Comment by elman22** [comment]
I would like to have this feature as well and all responses should be searchable, not just JSON.

**Comment by claudiatd** [comment]
Hi @elman22 :) Thank you for the suggestion! This feature is on our radar and it's definitely coming. I'll keep you posted :)

**Comment by jakubroztocil** [comment]
Thanks for the feedback, everyone! We’ve just shipped search 👉 https://httpie.io/blog/changelog-0019

![image](https://user-images.githubusercontent.com/326885/192599417-4a9b82f1-3e89-413c-b8ff-d6776dcfc0e6.png)
