### ISSUE TITLE
Feature request: Copy request for usage with command line httpie

### ISSUE THREAD

**Issue by elman22** [httpie/desktop#24]
## Checklist

[x] I've searched for similar feature requests.

## Enhancement request

Option to copy request for usage with command line httpie

## Problem it solves

Enables me to use request on different computer / server without httpie desktop and without having to create it from scratch.

## Additional information, screenshots, or code examples

…

**Comment by jakubroztocil** [comment]
Hi @elman22 , we have this feature inside the Preview panel:

<img width="1313" alt="Screenshot 2022-06-14 at 13 52 36" src="https://user-images.githubusercontent.com/326885/173571096-1493b83a-4f38-447d-8fdb-f95bd6684759.png">

**Comment by elman22** [comment]
Awesome. Thanks for quick reply :smiley:
