### ISSUE TITLE
License for this app?

### ISSUE THREAD

**Issue by dit7ya** [httpie/desktop#32]
Sorry if I am missing something but I cannot seem to find the License for the desktop app anywhere. Could you please add the relevant license to this repo? Also, if it is open-source, could you please also include the build instructions?

**Comment by jakubroztocil** [comment]
Hey @dit7ya, in this repo, we only publish releases. The app might become open source in the future.

**Comment by martin-braun** [comment]
@jakubroztocil May I ask why the desktop app is not open source? Proprietary software brings all kinds of problems. Would love to hear an official statement why this isn't possible or when it will be done. 

Thanks a lot in advance!

**Comment by elliott-sh** [comment]
Make it free sofware!

**Comment by elliott-sh** [comment]
> Make it free sofware!

Its as easy as merging #71 and adding source code
