### ISSUE TITLE
[Bug]: Microsoft Defender SmartScreen popup warning on Windows

### ISSUE THREAD

**Issue by sourcedelica** [httpie/desktop#33]
### What happened?

When trying to run `HTTPie-Setup-2022.12.0.exe` on Windows 10 I get a popup that reads:
```
Windows protected your PC

Microsoft Defender SmartScreen prevented an unrecognized app from starting.  Running this app might put your PC at risk.

App: HTTPie-Setup-2022.12.0.exe
Publisher: Unknown publisher

Run Anyway?    Don't Run
```
Is this expected? 

Looking at https://stackoverflow.com/questions/48946680/how-to-avoid-the-windows-defender-smartscreen-prevented-an-unrecognized-app-fro it looks like maybe it doesn't have an Extended Validation signing certificate?  

### Steps to reproduce?

```Markdown
1. Run `HTTPie-Setup-2022.12.0.exe`
2. Get the popup
```

### What did you expect to happen?

I expected it to install normally.

### Platform

Windows

### HTTPie Desktop version

2022.12.0

### Relevant log output

```Shell
Where is the log?
```

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by jakubroztocil** [comment]
@sourcedelica thanks for the report! It’s in our backlog, and hopefully, already the next Windows release will be signed.

**Comment by sourcedelica** [comment]
Cool - thanks.

**Comment by irg1008** [comment]
Still happening

![image](https://github.com/httpie/desktop/assets/47559427/63b12267-4a74-4ce3-9b85-546f158610a9)

**Comment by DanielRouxSA** [comment]
Still happening on 2023.3.5
