### ISSUE TITLE
[Bug]: Sending big files (500MB+) causes Unhandled internal error occurred

### ISSUE THREAD

**Issue by astravexton** [httpie/desktop#35]
### What happened?

When trying to send a big file over 500MB (don't know the exact limit), the right panel shows "Unhandled internal error occurred" and no request is actually sent on the receiver side

![image](https://user-images.githubusercontent.com/3042219/188434190-76e3f23f-eb1d-4aa9-90c1-19646e63b38d.png)

### Steps to reproduce?

```Markdown
1. Set POST request and enter URL (Using a public domain pointing to a server where I do dev work on)
2. Go to Body tab, pick "File" and choose a file that is 500MB or bigger
3. Press "Send" and wait for error to show
```

### What did you expect to happen?

I expected it to send the file and give a response, as it works fine with `httpie` CLI, `curl`, and `wget`. On closer look I can see that all requests are getting proxied through AWS servers which isn't mentioned anyway, causing issues when trying to test big file uploads, as well as other things like the request IP not coming from where you expect

### Platform

Windows

### HTTPie Desktop version

2022.13.0

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by psd-coder** [comment]
Could you clarify, do you use web version of HTTPie and not desktop app? Web version proxies request to avoid browser cross domains requests limitations but proxy server has own body size limits. To get rid of that limitation you should use [HTTPie desktop app](https://httpie.io/download). We definitely should better handle this case in web version, thank you for the report!
