### ISSUE TITLE
Editing title doesn't work

### ISSUE THREAD

**Issue by t1** [httpie/desktop#4]
I have a request in my collection named `:8080/wunderbar-mock-server/graphql`. When I open the `Edit...` menu item, I can't change the value, not even move the cursor.

**Comment by jakubroztocil** [comment]
@t1 thanks for the report! Do you happen to have some password manager installed that might be interfering with the field? We have seen something similar in the past.

**Comment by t1** [comment]
I'm using Safari on a M1 Mac, so I have the built in Keychain, but it also happens in the desktop app

**Comment by claudiatd** [comment]
@t1 given there's no name, the URL is used as a request identifier. When you open `Edit...` then the URL is also shown as a placeholder. You can't change the placeholder, but you can write any other name instead. Could you try it out please?

If this is the case, I understand it isn't very clear. We'll circle back for improvements. Thanks for the report!

**Comment by t1** [comment]
You are right!!! All the other text on the dialog is in a similar grey, so I didn't expect this to be just the placeholder. When I start typing, it's bright white. Probably tweaking the colors would be sufficient for even noobs like me to get it. Thanks!

**Comment by claudiatd** [comment]
That's a good suggestion! We'll re-check the colors :) Thank you!
