### ISSUE TITLE
Generate  Client Code

### ISSUE THREAD

**Issue by justmd5** [httpie/desktop#45]
Generate  Client Code like the tool Insomnia,thks

**Comment by claudiatd** [comment]
@justmd5 code generation is already possible. Find it in the preview panel. Thanks :)
<img width="1089" alt="Screen Shot 2022-10-25 at 15 14 20" src="https://user-images.githubusercontent.com/1515593/197798028-4db1b6bc-d8c5-4485-a8c8-78586a9d1295.png">
