### ISSUE TITLE
[Bug] Pasted curl request cannot be parsed correctly

### ISSUE THREAD

**Issue by ripley** [httpie/desktop#49]
Looks like it's supported since if I paste a curl request httpie app asked to edit then save the request.

But the app failed to handle a vanilla request like below:

`
curl 'https://some.url.org/v2/content/search' \
-H 'authority: api.staging.dpa0.org' \
--data-raw '{"entities_by_integration": {"internal": ["experiencescore_org"]}}' \
--compressed
`

A same request could be handled in apps like insomnia correctly.

**Comment by 11bit** [comment]
Looks like the curl command is slightly incorrect (at least it doesn't run in my terminal): 
1. `\` should either be removed or line break inserted
2. It needs content type to send it as json

So, if I fix this two issues I can both send it in terminal and import to httpie:
```
curl 'https://some.url.org/v2/content/search' \
 -H 'authority: api.staging.dpa0.org' \
 -H 'Content-type: application/json' \
 --data-raw '{"entities_by_integration": {"internal": ["experiencescore_org"]}}' \
 --compressed
```

**Comment by ripley** [comment]
I reviewed it again and here is a failing curl, I think it's related with the special format of `--data-raw` argument. Didn't get to spot the exact issue though.

This is a curl I copied out from chrome browser dev tool.

`curl 'https://api.staging.dpa0.org/v2/widgets/standard/preview' \
  -H 'authority: api.staging.dpa0.org' \
  -H 'accept: application/json, text/plain, */*' \
  -H 'accept-language: en-US,en;q=0.9,zh-Hans;q=0.8,zh-Hant;q=0.7,zh;q=0.6' \
  -H 'content-type: application/json' \
  -H 'cookie: API_URL=https%3A%2F%2Fapi.staging.dpa0.org' \
  -H 'origin: https://staging.dpa0.org' \
  -H 'referer: https://staging.dpa0.org/' \
  -H 'sec-ch-ua: "Chromium";v="104", " Not A;Brand";v="99"' \
  -H 'sec-ch-ua-mobile: ?0' \
  -H 'sec-ch-ua-platform: "macOS"' \
  -H 'sec-fetch-dest: empty' \
  -H 'sec-fetch-mode: cors' \
  -H 'sec-fetch-site: same-site' \
  -H 'user-agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/104.0.5112.126 Safari/537.36' \
  -H 'x-client-tzoffset: +08:00' \
  -H 'x-transaction-id: nq2fgw3ji' \
  -H 'x-xsrf-token: 467bcaa2-bb1d-469a-a511-f024ff538e9d' \
  --data-raw $'{"DEEM_ORG_UX_SCORE":{"trend_mode":"HISTORICAL","accumulate":false,"date_range":{"trend_span":{"duration":7,"unit":"DAYS"},"sampling_frequency":{"duration":1,"unit":"DAYS"},"start_date_millis":0,"end_date_millis":0,"date_range_order":"DESC","date_attribute_name":"internal.experiencescore_org.adp_modified_at","round_end_timestamp":false},"bucketing_attributes":["internal.experiencescore_org._org_overall_score"],"counter_definitions":[{"aggregate_attribute":"internal.experiencescore_org.event_type","aggregation_function":"COUNT_DISTINCT"}],"entities_by_integration":{"internal":["experiencescore_org"]},"cardinality":5},"DEEM_USER_UX_SCORE":{"trend_mode":"HISTORICAL","accumulate":false,"date_range":{"trend_span":{"duration":7,"unit":"DAYS"},"sampling_frequency":{"duration":1,"unit":"DAYS"},"start_date_millis":0,"end_date_millis":0,"date_range_order":"DESC","date_attribute_name":"internal.experiencescore_user.adp_modified_at","round_end_timestamp":false},"bucketing_attributes":["internal.experiencescore_user._user_overall_score"],"counter_definitions":[{"aggregate_attribute":"internal.experiencescore_user.user_guid","aggregation_function":"COUNT_DISTINCT"}],"entities_by_integration":{"internal":["experiencescore_user"]},"cardinality":5},"DEEM_DESKTOP_APPS_UX_SCORE":{"trend_mode":"HISTORICAL","accumulate":false,"date_range":{"trend_span":{"duration":7,"unit":"DAYS"},"sampling_frequency":{"duration":1,"unit":"DAYS"},"start_date_millis":0,"end_date_millis":0,"date_range_order":"DESC","date_attribute_name":"internal.experiencescore_desktop_app.adp_modified_at","round_end_timestamp":false},"bucketing_attributes":["internal.experiencescore_desktop_app._desktop_app_overall_score"],"counter_definitions":[{"aggregate_attribute":"internal.experiencescore_desktop_app._application_name","aggregation_function":"COUNT_DISTINCT"}],"entities_by_integration":{"internal":["experiencescore_desktop_app"]},"filter":"internal.experiencescore_desktop_app._desktop_app_overall_score IN (\'Neutral\', \'Poor\')","cardinality":5},"DEEM_MOBILE_APPS_UX_SCORE":{"trend_mode":"HISTORICAL","accumulate":false,"date_range":{"trend_span":{"duration":7,"unit":"DAYS"},"sampling_frequency":{"duration":1,"unit":"DAYS"},"start_date_millis":0,"end_date_millis":0,"date_range_order":"DESC","date_attribute_name":"internal.experiencescore_mobile_app.adp_modified_at","round_end_timestamp":false},"bucketing_attributes":["internal.experiencescore_mobile_app._mobile_app_overall_score"],"counter_definitions":[{"aggregate_attribute":"internal.experiencescore_mobile_app.app_config_app_name","aggregation_function":"COUNT_DISTINCT"}],"entities_by_integration":{"internal":["experiencescore_mobile_app"]},"filter":"internal.experiencescore_mobile_app._mobile_app_overall_score IN (\'Neutral\', \'Poor\')","cardinality":5},"DEEM_DEVICE_HEALTH":{"trend_mode":"HISTORICAL","accumulate":false,"date_range":{"trend_span":{"duration":7,"unit":"DAYS"},"sampling_frequency":{"duration":1,"unit":"DAYS"},"start_date_millis":0,"end_date_millis":0,"date_range_order":"DESC","date_attribute_name":"internal.experiencescore_device.adp_modified_at","round_end_timestamp":false},"bucketing_attributes":["internal.experiencescore_device._device_overall_score"],"counter_definitions":[{"aggregate_attribute":"internal.experiencescore_device.device_guid","aggregation_function":"COUNT_DISTINCT"}],"entities_by_integration":{"internal":["experiencescore_device"]},"filter":"internal.experiencescore_device._device_overall_score IN (\'Neutral\', \'Poor\')","cardinality":5}}' \
  --compressed
`

**Comment by 11bit** [comment]
Yeah, looks like it now uses [ANSI-C Quoting](https://www.gnu.org/software/bash/manual/html_node/ANSI_002dC-Quoting.html) ($'...') for `--data-raw` attribute which we currently do not support. So the app adds a `$` symbol at the beginning and doesn't interpolate escape sequences.

Thanks for the report! We will have a look at improving it.

**Comment by ripley** [comment]
Sure, looking forward to your new features !

**Comment by jakubroztocil** [comment]
This has been fixed — thanks for the report!
