### ISSUE TITLE
Support GraphQL

### ISSUE THREAD

**Issue by t1** [httpie/desktop#5]
I already ❤️ the httpie cli. The App looks also very promising. But I can't switch to it, yet, as we work extensively with GraphQL and the support in, e.g., Insomnia is really good.

I know this is not a small thing, but it should be in the backlog 😁

**Comment by jakubroztocil** [comment]
Yes, it’s already in the backlog 😄  Please stay tuned, and thanks for the kind words!

**Comment by jakubroztocil** [comment]
@t1  We’ve just shipped GraphQL support in [HTTPie for Web & Desktop v2022.12.0](https://github.com/httpie/desktop/releases/tag/v2022.12.0) 🙌

![image](https://user-images.githubusercontent.com/326885/184079001-cc1583bc-68c6-4fc1-aee2-eb08793bc06f.png)

**Comment by t1** [comment]
It looks nice. A good next step would be to show the schema and to support auto-completion from the schema.

**Comment by jakubroztocil** [comment]
@t1 that’s exactly the plan, please stay tuned 😎
