### ISSUE TITLE
Unable to cancel stalled request

### ISSUE THREAD

**Issue by iAmWillShepherd** [httpie/desktop#6]
I was developing an API and noticed that you can't cancel a stalled request. It seems that you thought of this already, its just that it doesn't work. 

![2022-02-26 13 29 41](https://user-images.githubusercontent.com/1715082/155856544-47d6dd0f-b4d1-4527-8229-7fabdd80ac3f.gif)

There is a workaround for this behavior, but it requires me to close the tab and lose all my work.

Btw, an issue template or form would be super helpful.

**Comment by iAmWillShepherd** [comment]
I submitted https://github.com/httpie/desktop/pull/7 to fix the lack of issue form.

**Comment by jakubroztocil** [comment]
@iAmWillShepherd we’ve released a new version that fixes this. Could you please verify it?

**Comment by jakubroztocil** [comment]
@iAmWillShepherd We’ve [just released 2022.7.0](https://httpie.io/blog/changelog-0014) where this issue should is fixed.
