### ISSUE TITLE
License

### ISSUE THREAD

**Issue by Meow-purr** [httpie/desktop#72]
What is the license?

checklist

- [ ] merge #71
- [ ] add source code

**Comment by cprivitere** [comment]
It's fine if it's closed source too, but there's still no licensing terminology whatsoever in the app and no EULA when you open it. So i guess...we're all free to repulish it and rehost it and do whatever we want with it?

**Comment by elliott-sh** [comment]
> It's fine if it's closed source too, but there's still no licensing terminology whatsoever in the app and no EULA when you open it. So i guess...we're all free to repulish it and rehost it and do whatever we want with it?

@cprivitere 

i guess ill decompile then

**Comment by cprivitere** [comment]
Oh ha, I hadn't even noticed the source code is attached as an asset to the release as well. So confused.

**Comment by cprivitere** [comment]
These terms don't refer to your desktop program at all. And the only applications they refer to are mobile ones. This application runs on a PC.

**Comment by Meow-purr** [comment]
> These terms don't refer to your desktop program at all. And the only applications they refer to are mobile ones. This application runs on a PC.
@cprivitere 

still gona dissasemble

**Comment by Meow-purr** [comment]
also i got httpie before the terms were in place

**Comment by jakubroztocil** [comment]
@cprivitere see the second sentence on the page:

> This page explains the terms by which you may use our online and/or mobile services, web site, **and software provided on or in connection with the service (collectively, the “Service”)**

@Meow-purr the terms have been on the website, which is linked from our GitHub, since before the 1st release of the desktop app.
