### ISSUE TITLE
Add link follows in responses

### ISSUE THREAD

**Issue by qu1rk3y** [httpie/desktop#8]
It would be great to have the option to follow links that present in responses as GETs in new tabs please!

![image](https://user-images.githubusercontent.com/791671/155997140-4f7d65d7-73a9-46c4-952a-42c6406a9510.png)

**Comment by jakubroztocil** [comment]
Thanks, @qu1rk3y. It’s in our backlog.

**Comment by jakubroztocil** [comment]
@qu1rk3y Thank you for your feedback. We’ve just released a new version that adds interactivity to URLs.

👉 See full changelog: https://httpie.io/blog/changelog-0018

![image](https://user-images.githubusercontent.com/326885/187270716-ff50b668-2cc6-441d-ae84-8c62439b2763.png)
