### ISSUE TITLE
[Bug]: Cannot detect value https:// in variable

### ISSUE THREAD

**Issue by nguyenphutrong** [httpie/desktop#80]
### What happened?

Cannot detect value https:// in variable

If my env variable is **https://example.com,** it will be **http://https://example.com**

![httpie-bug-report](https://github.com/httpie/desktop/assets/62984954/ae98655a-1493-4283-b902-f605f66d369d)

### Steps to reproduce?

```Markdown
Call API with variable
```

### What did you expect to happen?

Make it work

### Platform

macOS

### HTTPie Desktop version

2023.2.1

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by jakubroztocil** [comment]
Thanks for the report! We'll be making another bug fix release today.
