### ISSUE TITLE
[Bug]: Update message keeps popping up

### ISSUE THREAD

**Issue by Henkoglobin** [httpie/desktop#81]
### What happened?

When there's an update available. HTTPie Desktop will ask the user to install it. Clicking the 'Ask on next launch' button (I don't remember the exact wording ATM) will close the dialog, but it'll keep popping up every few minutes.

### Steps to reproduce?

```Markdown
1. Have an update available
2. Click 'Ask on next launch' (or whatever the button is called exactly)
3. Wait a few minutes
4. The dialog will pop up again
```

### What did you expect to happen?

No update dialog should be shown until HTTPie Desktop is launched again.

### Platform

Windows

### HTTPie Desktop version

2023.2.4

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by jakubroztocil** [comment]
Hey @Henkoglobin, thanks for the report. We fixed it in [v2023.2.4](https://github.com/httpie/desktop/releases/tag/v2023.2.4), so while upgrading to this version, it was hopefully the last time you experienced the issue.
