### ISSUE TITLE
[Bug]: Lost saved collection after upgrading to 2023.2.4

### ISSUE THREAD

**Issue by haunt98** [httpie/desktop#82]
### What happened?

I lost all my saved collection API after upgrading to 2023.2.4

### Steps to reproduce?

```Markdown
1. Launch the app
2. Click install now when update pop up shows
3. The app relaunches but collection is gone
```

### What did you expect to happen?

Saved collection is still be there.

### Platform

None

### HTTPie Desktop version

2023.2.4

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by jakubroztocil** [comment]
@haunt98 thanks for the report and sorry for the trouble We’re looking into it

**Comment by aiven715** [comment]
@haunt98, there is a slight possibility that the space selection may be changed after the data migration. Could you please verify that you are currently on the correct one?

**Comment by haunt98** [comment]
Thanks @aiven715, I see my old collection in Incognito space now.

<img width="337" alt="image" src="https://github.com/httpie/desktop/assets/5424272/6e8f56b8-648c-4371-802a-e75a7993d4e8">

**Comment by aiven715** [comment]
@haunt98 you're welcome 🙌 

You can move a collection to another space using the context menu.

<img width="368" alt="Move to space" src="https://github.com/httpie/desktop/assets/44402489/9d459ad2-e125-429d-b057-3e91507f9fc3">

**Comment by haunt98** [comment]
Nice tips, thanks @aiven715 for showing me 💯
