### ISSUE TITLE
[Bug]: Desktop Version don't open on Ubuntu 23.04

### ISSUE THREAD

**Issue by hiroyamaguch** [httpie/desktop#90]
### What happened?

I've try to run HTTPie on linux and don't works. I try some options:

- [AppImageLauncher](https://github.com/TheAssassin/AppImageLauncher)
- [x] .deb install
- [x] PPAs install
- [GearLever](https://flathub.org/apps/it.mijorus.gearlever)

### Steps to reproduce?

```Markdown
1. Install app
2. Click to open
3. Nothing happens
```

### What did you expect to happen?

The app open and works

### Platform

Linux

### HTTPie Desktop version

HTTPie -> 2023.3.0
Ubuntu -> 23.04

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by enboig** [comment]
Same for ubuntu 22.04. I downloaded file, chmod 700 and run:
```
$ ./HTTPie-2023.3.6-arm64.AppImage 
[appimage-binfmt-bypass/bin] ERROR: failed to execute patched runtime: Exec format error
```

**Comment by patelharsh9797** [comment]
Any update on this? 
Still haveing the same `appimage-binfmt-bypass/bin` error as of Jun 15, 2024.

**Comment by hiroyamaguch** [comment]
Keeps happening on ubuntu 24.04

**Comment by Mohsen-Khodabakhshi** [comment]
Same error on Ubuntu 22.04.

**Comment by hiroyamaguch** [comment]
I solve the problem executing this command `sudo apt install libfuse2t64`. 

I have discover the solution executing the application on terminal and seeing the error logs.

Link: https://github.com/AppImage/AppImageKit/wiki/FUSE.

**Comment by gsmetal** [comment]
I am still having this error. `libfuse` is installed
